/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env=production --include-runtime=false --env-interface=CloudflareProductionEnv worker-configuration.production.d.ts` (hash: d187f5b27adc406a6eedf3be0ce64531)
interface __BaseEnv_CloudflareProductionEnv {
	NEXT_INC_CACHE_R2_BUCKET: R2Bucket;
	ASSETS: Fetcher;
	WORKER_SELF_REFERENCE: Service<typeof import("./.open-next/worker").default>;
	CLOUD_WORKER: Fetcher /* cloud-worker */;
	VISITS_WORKER: Fetcher /* visits-worker */;
	PORTFOLIO_STATE: Fetcher /* portfolio-state-worker */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
	}
	interface Env extends __BaseEnv_CloudflareProductionEnv {}
}
interface CloudflareProductionEnv extends __BaseEnv_CloudflareProductionEnv {}
