/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env=preview --include-runtime=false --env-interface=CloudflarePreviewEnv worker-configuration.preview.d.ts` (hash: f7cd5abae4ba7a207aba977087d61001)
interface __BaseEnv_CloudflarePreviewEnv {
	NEXT_INC_CACHE_R2_BUCKET: R2Bucket;
	ASSETS: Fetcher;
	WORKER_SELF_REFERENCE: Service<typeof import("./cloudflare-worker").default>;
	CLOUD_WORKER: Fetcher /* cloud-worker */;
	VISITS_WORKER: Fetcher /* visits-worker */;
	PORTFOLIO_STATE: Fetcher /* portfolio-state-worker */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./cloudflare-worker");
	}
	interface Env extends __BaseEnv_CloudflarePreviewEnv {}
}
interface CloudflarePreviewEnv extends __BaseEnv_CloudflarePreviewEnv {}
