/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env=production --include-runtime=false --env-interface=CloudflareProductionEnv worker-configuration.production.d.ts` (hash: 220b5019539468f2781ad110824c0499)
interface __BaseEnv_CloudflareProductionEnv {
	NEXT_INC_CACHE_R2_BUCKET: R2Bucket;
	ASSETS: Fetcher;
	WORKER_SELF_REFERENCE: Service<typeof import("./cloudflare-worker").default>;
	CLOUD_WORKER: Fetcher /* cloud-worker */;
	VISITS_WORKER: Fetcher /* visits-worker */;
	PORTFOLIO_STATE: Fetcher /* portfolio-state-worker */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./cloudflare-worker");
	}
	interface Env extends __BaseEnv_CloudflareProductionEnv {}
}
interface CloudflareProductionEnv extends __BaseEnv_CloudflareProductionEnv {}
